# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c4f431e9e4ec727b780a9069a1713bfecb2822b803fb7599a4810d0a83dd9d9fc9e1306c326d39ded2e0155eba65dfd344a449985fca0a5a0911585f87d9f71

test:
  secret_key_base: b3b975ceee64e179daebba13817e628f23190773d30e06de3e7cf23d46679e279b253215bd9d16371c260e9022f4f2526d38ce7b9cd0387a47ec4616c8993d27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
